export { default as HomeScreen } from './HomeScreen';
export { default as TeacherScreen } from './TeacherScreen';
export { default as StudentScreen } from './StudentScreen';
export { default as NewQuestionScreen } from './NewQuestionScreen';
export { default as NewClassScreen } from './NewClassScreen';
export { default as ClassesScreen } from './ClassesScreen';
export { default as QuizzesScreen } from './QuizzesScreen';
export { default as ClassDetailScreen } from './ClassDetailScreen';
export { default as QuizDetailScreen } from './QuizDetailScreen';